"""auto update

Revision ID: 24b52734619c
Revises: 98c082c26e17
Create Date: 2026-05-07 03:50:52.029656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b52734619c'
down_revision: Union[str, Sequence[str], None] = '98c082c26e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'customer_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ticket_messages', 'sender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tickets', 'ticket_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tickets', 'customer_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'customer_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tickets', 'ticket_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ticket_messages', 'sender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('invoices', 'customer_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###