"""auto update

Revision ID: 494c52829144
Revises: 7657fb51801b
Create Date: 2026-04-30 02:52:53.965471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '494c52829144'
down_revision: Union[str, Sequence[str], None] = '7657fb51801b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.VARCHAR(),
               server_default='default',
               nullable=True)
    op.alter_column('user_daily_quota', 'question_count',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=False)
    op.alter_column('user_daily_quota', 'plan',
               existing_type=sa.VARCHAR(),
               server_default='unlimited',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_daily_quota', 'plan',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_daily_quota', 'question_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.VARCHAR(),
               server_default=None,
               nullable=False)
    # ### end Alembic commands ###