"""auto update

Revision ID: a26ad3fbd3b3
Revises: d433a27b996f
Create Date: 2026-05-07 05:34:31.061575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a26ad3fbd3b3'
down_revision: Union[str, Sequence[str], None] = 'd433a27b996f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gateway_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('gateway_name', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('connection_status_before', sa.String(), nullable=True),
    sa.Column('connection_status_after', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gateway_audit_logs_id'), 'gateway_audit_logs', ['id'], unique=False)
    op.create_table('payment_gateway_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gateway_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('api_key_encrypted', sa.String(), nullable=True),
    sa.Column('secret_key_encrypted', sa.String(), nullable=True),
    sa.Column('public_key_encrypted', sa.String(), nullable=True),
    sa.Column('webhook_secret_encrypted', sa.String(), nullable=True),
    sa.Column('merchant_id', sa.String(), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('supported_currencies', sa.String(), nullable=True),
    sa.Column('supported_countries', sa.String(), nullable=True),
    sa.Column('payment_methods', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('last_test_at', sa.String(), nullable=True),
    sa.Column('last_test_status', sa.String(), nullable=True),
    sa.Column('last_successful_payment_at', sa.String(), nullable=True),
    sa.Column('connection_status', sa.String(), nullable=True),
    sa.Column('settings_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_gateway_settings_id'), 'payment_gateway_settings', ['id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gateway_name', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('signature_valid', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_id'), 'webhook_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_events_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_payment_gateway_settings_id'), table_name='payment_gateway_settings')
    op.drop_table('payment_gateway_settings')
    op.drop_index(op.f('ix_gateway_audit_logs_id'), table_name='gateway_audit_logs')
    op.drop_table('gateway_audit_logs')
    # ### end Alembic commands ###